spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./database/data;AUTO_SERVER=TRUE
    username: sa
    password: 123456
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: h2
  thymeleaf:
    cache: true
    encoding: UTF-8 # 模板编码
    prefix: file:templates/template1/
    suffix: .html # 构建URL时附加到查看名称的后缀
    mode: HTML # 模板模式
    enabled: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 5GB
  security:
    user:
      name: admin
      roles: admin
      password: 123456
    general-user-url:
      - /api/v1/card/icons
      - /api/v1/card/icon
      - /api/v1/card
      - /api/v1/upload/*
      - /api/v1/category/tree
      - /api/v1/app/version
      - /api/v1/user/password
    permit-url:
      - /docs/**
      - /assets/**
      - /api/v1/card/tree
      - /api/v1/notice
      - /api/v1/qrcode
      - /api/v1/attachment/*/actions/download
      - /api/v1/setting
      - /api/v1/quick/login
      - /api/v1/login/user
      - /api/v1/user/star/card
      - /login
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always
# 日志相关的配置，还有些问题，后续要改成xml的方式来配置.
logging:
  file:
    name: logs/team-nav.log
  level:
    root: info
    org:
      apache: error
      springframework: error

# 线程池配置
thread-pool:
  core-pool-num: 2
  max-pool-num: 2

# 服务名，用于页面logo显示
nav-name: 团队服务导航

# 是否开启定时清没有使用的文件
clear-useless-files:
  enable: false
  cron: 0 0 1 * * ?

project:
  remote-version-url: https://gitee.com/tuituidan/team-nav/releases/latest
  version: @project.version@
